name: Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  monitor:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - run: python query.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
